# Generated by Django 4.0.2 on 2022-03-21 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=6)),
                ('weight', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
                ('dateAdded', models.DateField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(default=datetime.datetime.utcnow)),
                ('receipt', models.CharField(max_length=50, null=True)),
                ('amount', models.FloatField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('checkoutReuestID', models.CharField(max_length=50)),
                ('merchantRequestId', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPaid', models.BooleanField(default=False)),
                ('isDelivered', models.BooleanField(default=False)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gas.catalogue')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gas.transactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
