# Generated by Django 4.0.2 on 2022-02-04 18:58

import datetime
from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('LARGE', 'Large'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=6)),
                ('weight', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
                ('dateAdded', models.DateField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
