# Generated by Django 4.0.2 on 2022-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0002_userregistrationmodel_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='phone_number',
            field=models.CharField(default=725328016, max_length=15),
            preserve_default=False,
        ),
    ]
