# Generated by Django 4.0.2 on 2022-02-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0003_profile_phone_number_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='receipt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
