# Generated by Django 4.0.2 on 2022-03-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0003_userregistrationmodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='phone_number',
        ),
    ]
